#!/usr/bin/env bash
set -euo pipefail
exec /Users/yorkin/.moon/bin/moonrun /Users/yorkin/source/moonbit/moonbit-debug-prototype/debug_deriving/target/wasm-gc/release/build/debug_deriving.wasm -- "$@"
